config/routes.rb
Rails.application.routes.draw do
  resources :mes
  devise_for :users
  root 'mes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/me.rb
class Me < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/mes_controller.rb
class MesController < ApplicationController
  before_action :set_me, only: [:show, :edit, :update, :destroy]

  # GET /mes
  # GET /mes.json
  def index
    @mes = Me.all
  end

  # GET /mes/1
  # GET /mes/1.json
  def show
  end

  # GET /mes/new
  def new
    @me = Me.new
  end

  # GET /mes/1/edit
  def edit
  end

  # POST /mes
  # POST /mes.json
  def create
    @me = Me.new(me_params)

    respond_to do |format|
      if @me.save
        format.html { redirect_to @me, notice: 'Me was successfully created.' }
        format.json { render :show, status: :created, location: @me }
      else
        format.html { render :new }
        format.json { render json: @me.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mes/1
  # PATCH/PUT /mes/1.json
  def update
    respond_to do |format|
      if @me.update(me_params)
        format.html { redirect_to @me, notice: 'Me was successfully updated.' }
        format.json { render :show, status: :ok, location: @me }
      else
        format.html { render :edit }
        format.json { render json: @me.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mes/1
  # DELETE /mes/1.json
  def destroy
    @me.destroy
    respond_to do |format|
      format.html { redirect_to mes_url, notice: 'Me was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_me
      @me = Me.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def me_params
      params.require(:me).permit(:que_piensa_y_siente, :que_ve, :que_oye, :que_dice_y_hace, :esfuerzos, :resultados, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mes_helper.rb
module MesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mes/_form.html.erb
<%= form_with(model: me, local: true) do |form| %>
  <% if me.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(me.errors.count, "error") %> prohibited this me from being saved:</h2>

      <ul>
      <% me.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :que_piensa_y_siente %>
    <%= form.text_area :que_piensa_y_siente %>
  </div>

  <div class="field">
    <%= form.label :que_ve %>
    <%= form.text_area :que_ve %>
  </div>

  <div class="field">
    <%= form.label :que_oye %>
    <%= form.text_area :que_oye %>
  </div>

  <div class="field">
    <%= form.label :que_dice_y_hace %>
    <%= form.text_area :que_dice_y_hace %>
  </div>

  <div class="field">
    <%= form.label :esfuerzos %>
    <%= form.text_area :esfuerzos %>
  </div>

  <div class="field">
    <%= form.label :resultados %>
    <%= form.text_area :resultados %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mes/edit.html.erb
<h1>Editing Me</h1>

<%= render 'form', me: @me %>

<%= link_to 'Show', @me %> |
<%= link_to 'Back', mes_path %>

app/views/mes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mes</h1>

<table>
  <thead>
    <tr>
      <th>Que piensa y siente</th>
      <th>Que ve</th>
      <th>Que oye</th>
      <th>Que dice y hace</th>
      <th>Esfuerzos</th>
      <th>Resultados</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mes.each do |me| %>
      <tr>
        <td><%= me.que_piensa_y_siente %></td>
        <td><%= me.que_ve %></td>
        <td><%= me.que_oye %></td>
        <td><%= me.que_dice_y_hace %></td>
        <td><%= me.esfuerzos %></td>
        <td><%= me.resultados %></td>
        <td><%= me.user %></td>
        <td><%= link_to 'Show', me %></td>
        <td><%= link_to 'Edit', edit_me_path(me) %></td>
        <td><%= link_to 'Destroy', me, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Me', new_me_path %>

app/views/mes/new.html.erb
<h1>New Me</h1>

<%= render 'form', me: @me %>

<%= link_to 'Back', mes_path %>

app/views/mes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Que piensa y siente:</strong>
  <%= @me.que_piensa_y_siente %>
</p>

<p>
  <strong>Que ve:</strong>
  <%= @me.que_ve %>
</p>

<p>
  <strong>Que oye:</strong>
  <%= @me.que_oye %>
</p>

<p>
  <strong>Que dice y hace:</strong>
  <%= @me.que_dice_y_hace %>
</p>

<p>
  <strong>Esfuerzos:</strong>
  <%= @me.esfuerzos %>
</p>

<p>
  <strong>Resultados:</strong>
  <%= @me.resultados %>
</p>

<p>
  <strong>User:</strong>
  <%= @me.user %>
</p>

<%= link_to 'Edit', edit_me_path(@me) %> |
<%= link_to 'Back', mes_path %>